using System.Collections.Generic;
using System.Globalization;
using System.Text;
using FigmaToUnity.Core;
using UnityEngine;

namespace FigmaToUnity.Editor.UitkPipeline
{
    // Walks a tagged FigmaNode tree and emits one USS document per root frame.
    // Each managed node gets a `#fig-<id>` selector with the geometry and visual
    // properties resolvable from DesignNode fields alone.
    //
    // V1 limitations (intentional; will revisit per plan §8 follow-ups):
    //   - Gradient fills are skipped (USS gradient support is partial in 2022.3).
    //   - Drop-shadow / blur effects are not emitted.
    //   - Per-character text style overrides collapse to the base TextStyle.
    //   - Mask nodes degrade to overflow:hidden via ClipBounds.
    //   - Font family is not resolved; UIToolkit picks the project default.
    //   - 9-slice sprites are emitted as normal background images for static fidelity.
    internal static class UssEmitter
    {
        public static string Emit(FigmaNode root)
        {
            StringBuilder sb = new();
            sb.AppendLine("/* Generated by FigmaToUnity. Do not hand-edit per-frame.");
            sb.AppendLine("   Put overrides in a sibling .uss that follows the generated file. */");
            sb.AppendLine();

            EmitRules(sb, root, parent: null);
            return sb.ToString();
        }

        private static void EmitRules(StringBuilder sb, FigmaNode node, FigmaNode? parent)
        {
            if (node.IgnoreNode || !UitkRenderPolicy.ShouldEmitElement(node.Design))
            {
                return;
            }

            string selector = "#" + UitkStyleMapper.ToUssId(node.Id);
            StringBuilder block = new();

            EmitGeometry(block, node, parent);
            EmitAutoLayout(block, node);
            EmitBackground(block, node);
            EmitBackgroundImage(block, node);
            EmitBorder(block, node);
            EmitClip(block, node);
            EmitOpacity(block, node);
            EmitText(block, node);
            EmitNinePatch(block, node);

            if (block.Length > 0)
            {
                sb.Append(selector).AppendLine(" {");
                sb.Append(block);
                sb.AppendLine("}");
                sb.AppendLine();
            }

            // Auto-layout item spacing turns into trailing margin on every
            // non-last child along the primary axis. 2022.3 has no `gap`.
            if (node.LayoutMode == "HORIZONTAL" || node.LayoutMode == "VERTICAL")
            {
                EmitItemSpacingChildRules(sb, node);
            }

            if (node.Children == null)
            {
                return;
            }

            foreach (FigmaNode child in node.Children)
            {
                EmitRules(sb, child, node);
            }
        }

        private static void EmitGeometry(StringBuilder block, FigmaNode node, FigmaNode? parent)
        {
            BoundingBox? box = node.AbsoluteBoundingBox;
            UitkElementBox elementBox = box != null
                ? UitkRenderPolicy.ResolveElementBox(
                    node.Design,
                    node.Sprite?.rect.width,
                    node.Sprite?.rect.height,
                    FigmaImportSettings.instance.SpriteScale)
                : new UitkElementBox(0f, 0f, 0f, 0f);
            if (box != null)
            {
                AppendProperty(block, "width", UitkStyleMapper.ToPx(elementBox.Width));
                AppendProperty(block, "height", UitkStyleMapper.ToPx(elementBox.Height));
            }

            // Normal children of auto-layout parents flow via flex. Figma
            // absolute-positioned children still need absolute USS positioning,
            // matching UGUI's LayoutElement.ignoreLayout handling.
            if (box != null && UitkRenderPolicy.ShouldPositionAbsolutely(node.Design, parent?.Design))
            {
                AppendProperty(block, "position", "absolute");
                if (parent?.AbsoluteBoundingBox != null)
                {
                    AppendProperty(block, "left", UitkStyleMapper.ToPx(box.X - parent.AbsoluteBoundingBox.X + elementBox.LeftOffset));
                    AppendProperty(block, "top", UitkStyleMapper.ToPx(box.Y - parent.AbsoluteBoundingBox.Y + elementBox.TopOffset));
                }
                else
                {
                    AppendProperty(block, "left", UitkStyleMapper.ToPx(elementBox.LeftOffset));
                    AppendProperty(block, "top", UitkStyleMapper.ToPx(elementBox.TopOffset));
                }
            }

            if (node.MinWidth.HasValue)
            {
                AppendProperty(block, "min-width", UitkStyleMapper.ToPx(node.MinWidth.Value));
            }
            if (node.MaxWidth.HasValue)
            {
                AppendProperty(block, "max-width", UitkStyleMapper.ToPx(node.MaxWidth.Value));
            }
            if (node.MinHeight.HasValue)
            {
                AppendProperty(block, "min-height", UitkStyleMapper.ToPx(node.MinHeight.Value));
            }
            if (node.MaxHeight.HasValue)
            {
                AppendProperty(block, "max-height", UitkStyleMapper.ToPx(node.MaxHeight.Value));
            }
        }

        private static void EmitAutoLayout(StringBuilder block, FigmaNode node)
        {
            string? flexDirection = UitkStyleMapper.ToFlexDirection(node.LayoutMode);
            if (flexDirection == null)
            {
                return;
            }

            AppendProperty(block, "flex-direction", flexDirection);

            string? justify = UitkStyleMapper.ToJustifyContent(node.PrimaryAxisAlignItems);
            if (justify != null)
            {
                AppendProperty(block, "justify-content", justify);
            }

            string? align = UitkStyleMapper.ToAlignItems(node.CounterAxisAlignItems);
            if (align != null)
            {
                AppendProperty(block, "align-items", align);
            }

            if (node.LayoutWrap == "WRAP")
            {
                AppendProperty(block, "flex-wrap", "wrap");
            }

            if (node.PaddingLeft.HasValue && node.PaddingLeft.Value != 0f)
            {
                AppendProperty(block, "padding-left", UitkStyleMapper.ToPx(node.PaddingLeft.Value));
            }
            if (node.PaddingRight.HasValue && node.PaddingRight.Value != 0f)
            {
                AppendProperty(block, "padding-right", UitkStyleMapper.ToPx(node.PaddingRight.Value));
            }
            if (node.PaddingTop.HasValue && node.PaddingTop.Value != 0f)
            {
                AppendProperty(block, "padding-top", UitkStyleMapper.ToPx(node.PaddingTop.Value));
            }
            if (node.PaddingBottom.HasValue && node.PaddingBottom.Value != 0f)
            {
                AppendProperty(block, "padding-bottom", UitkStyleMapper.ToPx(node.PaddingBottom.Value));
            }
        }

        private static void EmitItemSpacingChildRules(StringBuilder sb, FigmaNode node)
        {
            if (!node.ItemSpacing.HasValue || node.ItemSpacing.Value <= 0f || node.Children == null)
            {
                return;
            }

            float gap = node.ItemSpacing.Value;
            bool horizontal = node.LayoutMode == "HORIZONTAL";

            // Skip ignored children when walking so the "last visible child" rule matches the UXML.
            List<FigmaNode> visible = new();
            foreach (FigmaNode child in node.Children)
            {
                if (!child.IgnoreNode && UitkRenderPolicy.ShouldParticipateInAutoLayout(child.Design, node.Design))
                {
                    visible.Add(child);
                }
            }

            if (visible.Count <= 1)
            {
                return;
            }

            // Per-child rule (every visible child except the last gets a trailing margin).
            for (int i = 0; i < visible.Count - 1; i++)
            {
                FigmaNode child = visible[i];
                string selector = "#" + UitkStyleMapper.ToUssId(child.Id);
                string side = horizontal ? "margin-right" : "margin-bottom";
                sb.Append(selector).AppendLine(" {");
                sb.Append("  ").Append(side).Append(": ").Append(UitkStyleMapper.ToPx(gap)).AppendLine(";");
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        private static void EmitBackground(StringBuilder block, FigmaNode node)
        {
            // Text nodes use `fills` to express the FOREGROUND (text) color in
            // Figma's model — EmitText consumes it as `color`. Applying it here as
            // background-color would render the Label as a solid filled rectangle
            // sitting on top of identically-colored text (i.e. invisible glyphs).
            if (node.Tags.Contains(NodeTag.Text))
            {
                return;
            }

            if (UitkRenderPolicy.ShouldSuppressSolidBackground(node.Design, HasResolvedSprite(node)))
            {
                return;
            }

            if (TryEmitSolidFromList(block, node.Fills))
            {
                return;
            }

        }

        private static bool TryEmitSolidFromList(StringBuilder block, List<Paint>? paints)
        {
            if (paints == null)
            {
                return false;
            }

            foreach (Paint fill in paints)
            {
                if (fill.Visible == false)
                {
                    continue;
                }

                if (string.Equals(fill.Type, "SOLID", System.StringComparison.OrdinalIgnoreCase) && fill.Color != null)
                {
                    AppendProperty(block, "background-color", UitkStyleMapper.ToCssColor(fill.Color, fill.Opacity));
                    return true;
                }
            }

            return false;
        }

        private static void EmitBackgroundImage(StringBuilder block, FigmaNode node)
        {
            // The auto-tagger marks *every* frame with visible paints as NodeTag.Image
            // because UGUI needs a sprite to render any fill. UIToolkit doesn't — it has
            // native background-color. Emit `background-image: url(...)` ONLY when there
            // is real raster content (IMAGE-type paint or 9-slice sprite). Solid-fill
            // frames rely on EmitBackground's background-color, which is what makes the
            // brown header / orange chips actually show their color.
            if (UitkRenderPolicy.ShouldEmitRasterBackgroundImage(node.Design, HasResolvedSprite(node)))
            {
                AppendProperty(block, "background-image", $"url(\"project://database/{node.AssetPath}\")");

                string? scaleMode = UitkRenderPolicy.ResolveRasterBackgroundScaleMode(node.Design);
                if (scaleMode != null)
                {
                    AppendProperty(block, "-unity-background-scale-mode", scaleMode);
                }

                return;
            }

            // Button-tagged Figma nodes are emitted as VisualElements, but keep
            // their generated background clean for solid-color button art.
            if (node.Tags.Contains(NodeTag.Button))
            {
                AppendProperty(block, "background-image", "none");
            }
        }

        private static bool HasResolvedSprite(FigmaNode node)
        {
            return !string.IsNullOrWhiteSpace(node.AssetPath);
        }

        private static void EmitBorder(StringBuilder block, FigmaNode node)
        {
            // Figma emits a huge sentinel value (~1e7) for "pill" / fully-rounded
            // corners. The visual maximum is half the min dimension; clamping here
            // both prevents USS warnings about absurd lengths and matches what the
            // renderer would do anyway.
            float maxRadius = ResolveMaxCornerRadius(node);

            if (node.CornerRadius.HasValue && node.CornerRadius.Value > 0f)
            {
                float r = Mathf.Min(node.CornerRadius.Value, maxRadius);
                AppendProperty(block, "border-top-left-radius", UitkStyleMapper.ToPx(r));
                AppendProperty(block, "border-top-right-radius", UitkStyleMapper.ToPx(r));
                AppendProperty(block, "border-bottom-right-radius", UitkStyleMapper.ToPx(r));
                AppendProperty(block, "border-bottom-left-radius", UitkStyleMapper.ToPx(r));
            }
            else if (node.RectangleCornerRadii != null && node.RectangleCornerRadii.Count == 4)
            {
                AppendProperty(block, "border-top-left-radius", UitkStyleMapper.ToPx(Mathf.Min(node.RectangleCornerRadii[0], maxRadius)));
                AppendProperty(block, "border-top-right-radius", UitkStyleMapper.ToPx(Mathf.Min(node.RectangleCornerRadii[1], maxRadius)));
                AppendProperty(block, "border-bottom-right-radius", UitkStyleMapper.ToPx(Mathf.Min(node.RectangleCornerRadii[2], maxRadius)));
                AppendProperty(block, "border-bottom-left-radius", UitkStyleMapper.ToPx(Mathf.Min(node.RectangleCornerRadii[3], maxRadius)));
            }

            if (!UitkRenderPolicy.ShouldEmitStrokeBorder(node.Design) || node.Strokes == null || node.Strokes.Count == 0)
            {
                return;
            }

            Paint? firstSolidStroke = null;
            foreach (Paint stroke in node.Strokes)
            {
                if (stroke.Visible == false)
                {
                    continue;
                }

                if (string.Equals(stroke.Type, "SOLID", System.StringComparison.OrdinalIgnoreCase) && stroke.Color != null)
                {
                    firstSolidStroke = stroke;
                    break;
                }
            }

            if (firstSolidStroke == null)
            {
                return;
            }

            string strokeColor = UitkStyleMapper.ToCssColor(firstSolidStroke.Color!, firstSolidStroke.Opacity);
            AppendProperty(block, "border-top-color", strokeColor);
            AppendProperty(block, "border-right-color", strokeColor);
            AppendProperty(block, "border-bottom-color", strokeColor);
            AppendProperty(block, "border-left-color", strokeColor);

            if (node.IndividualStrokeWeights != null)
            {
                if (node.IndividualStrokeWeights.Top.HasValue)
                {
                    AppendProperty(block, "border-top-width", UitkStyleMapper.ToPx(node.IndividualStrokeWeights.Top.Value));
                }
                if (node.IndividualStrokeWeights.Right.HasValue)
                {
                    AppendProperty(block, "border-right-width", UitkStyleMapper.ToPx(node.IndividualStrokeWeights.Right.Value));
                }
                if (node.IndividualStrokeWeights.Bottom.HasValue)
                {
                    AppendProperty(block, "border-bottom-width", UitkStyleMapper.ToPx(node.IndividualStrokeWeights.Bottom.Value));
                }
                if (node.IndividualStrokeWeights.Left.HasValue)
                {
                    AppendProperty(block, "border-left-width", UitkStyleMapper.ToPx(node.IndividualStrokeWeights.Left.Value));
                }
            }
            else if (node.StrokeWeight.HasValue)
            {
                string w = UitkStyleMapper.ToPx(node.StrokeWeight.Value);
                AppendProperty(block, "border-top-width", w);
                AppendProperty(block, "border-right-width", w);
                AppendProperty(block, "border-bottom-width", w);
                AppendProperty(block, "border-left-width", w);
            }
        }

        private static float ResolveMaxCornerRadius(FigmaNode node)
        {
            BoundingBox? box = node.AbsoluteBoundingBox;
            if (box != null && box.Width > 0f && box.Height > 0f)
            {
                return Mathf.Min(box.Width, box.Height) * 0.5f;
            }

            // Defensive cap when dimensions are unavailable; any well-formed Figma
            // node has a bounding box, but be conservative just in case.
            return 9999f;
        }

        private static void EmitClip(StringBuilder block, FigmaNode node)
        {
            if (UitkRenderPolicy.ShouldClipContent(node.Design))
            {
                AppendProperty(block, "overflow", "hidden");
            }
        }

        private static void EmitOpacity(StringBuilder block, FigmaNode node)
        {
            if (node.Opacity.HasValue && node.Opacity.Value < 1f)
            {
                AppendProperty(block, "opacity", UitkStyleMapper.ToOpacity(node.Opacity.Value));
            }
        }

        private static void EmitText(StringBuilder block, FigmaNode node)
        {
            if (!node.Tags.Contains(NodeTag.Text) || node.Style == null || UitkRenderPolicy.ShouldRenderTextAsRasterImage(node.Design))
            {
                return;
            }

            AppendProperty(block, "margin-left", "0px");
            AppendProperty(block, "margin-right", "0px");
            AppendProperty(block, "margin-top", "0px");
            AppendProperty(block, "margin-bottom", "0px");
            AppendProperty(block, "padding-left", "0px");
            AppendProperty(block, "padding-right", "0px");
            AppendProperty(block, "padding-top", "0px");
            AppendProperty(block, "padding-bottom", "0px");
            AppendProperty(block, "white-space", UitkRenderPolicy.ResolveTextWhiteSpace(node.Design));

            TextStyle style = node.Style;
            if (style.FontSize > 0f)
            {
                AppendProperty(block, "font-size", UitkStyleMapper.ToPx(style.FontSize));
            }

            // First visible solid text fill becomes the foreground color.
            if (node.Fills != null)
            {
                foreach (Paint fill in node.Fills)
                {
                    if (fill.Visible == false)
                    {
                        continue;
                    }

                    if (string.Equals(fill.Type, "SOLID", System.StringComparison.OrdinalIgnoreCase) && fill.Color != null)
                    {
                        AppendProperty(block, "color", UitkStyleMapper.ToCssColor(fill.Color, fill.Opacity));
                        break;
                    }
                }
            }

            string? anchor = UitkStyleMapper.ToTextAnchor(style.TextAlignHorizontal, style.TextAlignVertical);
            if (anchor != null)
            {
                AppendProperty(block, "-unity-text-align", anchor);
            }

            if (style.LetterSpacing.HasValue && style.LetterSpacing.Value != 0f)
            {
                AppendProperty(block, "letter-spacing", UitkStyleMapper.ToPx(style.LetterSpacing.Value));
            }
        }

        private static void EmitNinePatch(StringBuilder block, FigmaNode node)
        {
            if (!node.Tags.Contains(NodeTag.NinePatch))
            {
                return;
            }

            Vector4 importedBorder = node.SpriteBorder;
            BoundingBox? box = node.AbsoluteBoundingBox;
            if (box == null)
            {
                return;
            }

            bool hasImportedSpriteBorder = importedBorder != Vector4.zero;
            if (!UitkRenderPolicy.ShouldEmitStyleSliceBorder(node.Design, hasImportedSpriteBorder))
            {
                return;
            }

            UitkSliceBorder normalized = hasImportedSpriteBorder
                ? UitkRenderPolicy.NormalizeSliceBorder(
                    box.Width,
                    box.Height,
                    importedBorder.x,
                    importedBorder.y,
                    importedBorder.z,
                    importedBorder.w)
                : UitkRenderPolicy.ResolveNinePatchSliceBorder(node.Design, FigmaImportSettings.instance.SpriteScale);

            if (normalized.Left == 0 && normalized.Bottom == 0 && normalized.Right == 0 && normalized.Top == 0)
            {
                return;
            }

            AppendProperty(block, "-unity-slice-left", FormatInt(normalized.Left));
            AppendProperty(block, "-unity-slice-bottom", FormatInt(normalized.Bottom));
            AppendProperty(block, "-unity-slice-right", FormatInt(normalized.Right));
            AppendProperty(block, "-unity-slice-top", FormatInt(normalized.Top));
        }

        private static string FormatInt(float value)
        {
            return ((int)System.Math.Round(value)).ToString(CultureInfo.InvariantCulture);
        }

        private static void AppendProperty(StringBuilder block, string property, string value)
        {
            block.Append("  ").Append(property).Append(": ").Append(value).AppendLine(";");
        }
    }
}
